from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import pytest

from orchestrator.consensus import DialecticConsensusEngine
from orchestrator.jailer import CodeSanitizer, WorkerJailer
from orchestrator.shared_memory import SharedMemoryEngine


def test_shared_memory_initialize_and_trace(tmp_path: Path) -> None:
    engine = SharedMemoryEngine(path=tmp_path / "memory" / "shared_context.json")
    context = engine.initialize()
    assert context.consensus_logs == []

    trace = engine.append_thought_trace(
        agent="claude-3.5",
        task="component-proposal",
        summary="Produced hero section proposal.",
        artifacts=["Hero.tsx"],
    )
    loaded = engine.load()
    assert trace.agent == "claude-3.5"
    assert loaded.thought_traces[-1].summary == "Produced hero section proposal."


@dataclass
class FakeModel:
    name: str
    outputs: list[str]

    def generate(self, *, prompt: str, context: dict) -> str:  # noqa: ARG002
        return self.outputs.pop(0)


def test_consensus_engine_approves_human_grade(tmp_path: Path) -> None:
    memory = SharedMemoryEngine(path=tmp_path / "memory" / "shared_context.json")
    engine = DialecticConsensusEngine(memory=memory, max_rounds=3)
    claude = FakeModel(name="claude", outputs=["Component draft"])
    gemini = FakeModel(name="gemini", outputs=["Needs stronger heading hierarchy"])
    deepseek = FakeModel(
        name="deepseek",
        outputs=["Approved as Human-Grade and lacks AI-slop."],
    )

    result = engine.run(
        component_request="landing hero",
        claude=claude,
        gemini=gemini,
        deepseek=deepseek,
    )
    assert result.approved is True
    assert result.rounds == 1
    assert memory.load().consensus_logs


def test_worker_jailer_blocks_path_escape_and_dangerous_code(tmp_path: Path) -> None:
    jailer = WorkerJailer(sandbox_root=tmp_path / "sandbox")
    with pytest.raises(ValueError):
        jailer.resolve_worker_path("worker-a", "../escape.py")

    with pytest.raises(ValueError):
        jailer.save_generated_code("worker-a", "safe.py", "import subprocess\nprint('bad')")

    output = jailer.save_generated_code("worker-a", "safe.py", "print('ok')\n")
    assert output.exists()


def test_code_sanitizer_detects_ai_template() -> None:
    sanitizer = CodeSanitizer()
    findings = sanitizer.scan("// Generated by ChatGPT placeholder component")
    assert findings
    assert findings[0].category == "ai_template"
