"""Filesystem jail and code sanitizer for worker output."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from clawteam.fileutil import atomic_write_text
from clawteam.paths import ensure_within_root, validate_identifier


@dataclass(slots=True)
class SanitizerFinding:
    """Single sanitizer finding raised during code inspection."""

    category: str
    detail: str


class CodeSanitizer:
    """Scans generated code for dangerous imports and low-quality AI boilerplate."""

    MALICIOUS_IMPORT_PATTERNS = [
        re.compile(r"\b(import|from)\s+(subprocess|socket|ctypes|pickle|marshal)\b"),
        re.compile(r"\bos\.(system|popen)\s*\("),
        re.compile(r"\beval\s*\("),
        re.compile(r"\bexec\s*\("),
    ]

    AI_SLOP_PATTERNS = [
        re.compile(r"generated by (chatgpt|ai)", re.IGNORECASE),
        re.compile(r"todo[:\s]+implement", re.IGNORECASE),
        re.compile(r"lorem ipsum", re.IGNORECASE),
        re.compile(r"placeholder component", re.IGNORECASE),
    ]

    def scan(self, source: str) -> list[SanitizerFinding]:
        """Return all sanitizer findings for generated source code."""
        findings: list[SanitizerFinding] = []
        for pattern in self.MALICIOUS_IMPORT_PATTERNS:
            if pattern.search(source):
                findings.append(
                    SanitizerFinding(
                        category="malicious_import",
                        detail=f"Matched blocked pattern: {pattern.pattern}",
                    )
                )
        for pattern in self.AI_SLOP_PATTERNS:
            if pattern.search(source):
                findings.append(
                    SanitizerFinding(
                        category="ai_template",
                        detail=f"Matched AI-template pattern: {pattern.pattern}",
                    )
                )
        return findings

    def ensure_clean(self, source: str) -> None:
        """Raise ValueError if any finding is detected."""
        findings = self.scan(source)
        if findings:
            details = "; ".join(f"{f.category}: {f.detail}" for f in findings)
            raise ValueError(f"Code sanitizer rejected generated output: {details}")


class WorkerJailer:
    """Restricts workers to /sandbox and sanitizes generated artifacts before saving."""

    def __init__(self, sandbox_root: Path | None = None, sanitizer: CodeSanitizer | None = None) -> None:
        self.sandbox_root = sandbox_root or (Path.cwd() / "sandbox")
        self.sandbox_root.mkdir(parents=True, exist_ok=True)
        self.sanitizer = sanitizer or CodeSanitizer()

    def resolve_worker_path(self, worker_name: str, relative_path: str) -> Path:
        """Resolve a worker-owned path inside the sandbox root."""
        validate_identifier(worker_name, "worker name")
        relative = Path(relative_path)
        return ensure_within_root(self.sandbox_root, worker_name, *relative.parts)

    def save_generated_code(self, worker_name: str, relative_path: str, source: str) -> Path:
        """Persist sanitized generated code under the worker jail."""
        self.sanitizer.ensure_clean(source)
        target = self.resolve_worker_path(worker_name, relative_path)
        target.parent.mkdir(parents=True, exist_ok=True)
        atomic_write_text(target, source)
        return target
